---
title: "sap parameters"
author: "Lucas A. Nell"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{sap parameters}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
devtools::load_all()
knitr::opts_chunk$set(collapse = TRUE, comment = "")
```

This vignette describes the arguments that can be changed for a given aphid--wasp 
population pair.

# Argument descriptions

- `aphid_density_0`: Starting aphid density.
- `aphid_surv_juv`: Aphid juvenile survival.
- `aphid_surv_adult`: Vector of aphid adult survivals by stage.
- `aphid_repro`: Vector of aphid reproductive rates by stage.
- `K`: Aphid density dependence.
- `wasp_density_0`: Starting wasp density.
- `K_y`: Wasp density dependence.
- `s_y`: Wasp adult daily survival.
- `wasp_sex_ratio`: Proportion of female wasps.
- `aphid_instar_days`: Vector of the number of stages (days) per aphid instar.
- `mum_days`: Vector for the number of days per parasitized-aphid stage. It should be 
  of length 2, representing stages where the parasitized aphid is alive and dead, 
  respectively.
- `rel_attack`: Vectof of relative wasp attack rates by aphid stage.
- `a`: Overall parasitoid attack rate.
- `k`: Aggregation parameter of the nbinom distribution.
- `h`: Parasitoid attack rate handling time.
- `attack_surv`: Vector of length 2 with survival rates of singly & multiply attacked 
  aphids, respectively.
- `sigma_x`: Environmental standard deviation for aphids.
- `sigma_y`: Environmental standard deviation for parasitoids.
- `rho`: Environmental correlation among instars.
- `demog_mult`: Multiplier for demographic stochasticity.
- `harvest_surv`: Survival rate for living aphids during a harvest.
- `disp_aphid`: Dispersal rate for aphids.
- `disp_wasp`: Dispersal rate for wasps.
- `disp_start`: Stage in which dispersal starts in aphids.
- `pred_rate`: Predation on aphids and mummies.



# Default values

| Argument name        | Default-value object                  | Default value                             |
|:---------------------|:--------------------------------------|:------------------------------------------|
| `aphid_density_0`    | `sap::populations$aphids_0`           |   `r sap::populations$aphids_0`           |
| `aphid_surv_juv`     | `sap::populations$surv_juv$high`      |   `r sap::populations$surv_juv$high`      |
| `aphid_surv_adult`   | `sap::populations$surv_adult$high`    |   `r sap::populations$surv_adult$high`    |
| `aphid_repro`        | `sap::populations$repro$high`         |   `r sap::populations$repro$high`         |
| `K`                  | `sap::populations$K`                  |   `r sap::populations$K`                  |
| `wasp_density_0`     | `sap::populations$wasps_0`            |   `r sap::populations$wasps_0`            |
| `K_y`                | `sap::populations$K_y`                |   `r sap::populations$K_y`                |
| `s_y`                | `sap::populations$s_y`                |   `r sap::populations$s_y`                |
| `wasp_sex_ratio`     | `sap::populations$sex_ratio`          |   `r sap::populations$sex_ratio`          |
| `aphid_instar_days`  | `sap::dev_times$instar_days$highT`    |   `r sap::dev_times$instar_days$highT`    |
| `mum_days`           | `sap::dev_times$mum_days`             |   `r sap::dev_times$mum_days`             |
| `rel_attack`         | `sap::wasp_attack$rel_attack$highT`   |   `r sap::wasp_attack$rel_attack$highT`   |
| `a`                  | `sap::wasp_attack$a`                  |   `r sap::wasp_attack$a`                  |
| `k`                  | `sap::wasp_attack$k`                  |   `r sap::wasp_attack$k`                  |
| `h`                  | `sap::wasp_attack$h`                  |   `r sap::wasp_attack$h`                  |
| `attack_surv`        | `NA`                                  |   `r c(1,1)`                              |
| `sigma_x`            | `sap::environ$sigma_x`                |   `r sap::environ$sigma_x`                |
| `sigma_y`            | `sap::environ$sigma_y`                |   `r sap::environ$sigma_y`                |
| `rho`                | `sap::environ$rho`                    |   `r sap::environ$rho`                    |
| `demog_mult`         | `NA`                                  |   `r 1`                                   |
| `harvest_surv`       | `sap::environ$harvest_surv`           |   `r sap::environ$harvest_surv`           |
| `disp_aphid`         | `sap::environ$disp_aphid`             |   `r sap::environ$disp_aphid`             |
| `disp_wasp`          | `sap::environ$disp_wasp`              |   `r sap::environ$disp_wasp`              |
| `disp_start`         | `sap::environ$disp_start$highT`       |   `r sap::environ$disp_start$highT`       |
| `pred_rate`          | `sap::environ$pred_rate`              |   `r sap::environ$pred_rate`              |

