# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logit <- function(p) {
    .Call('_sappp_logit', PACKAGE = 'sappp', p)
}

inv_logit <- function(a) {
    .Call('_sappp_inv_logit', PACKAGE = 'sappp', a)
}

