---
title: "Meisner model"
author: "Lucas Nell"
date: "8/27/2017"
output: 
  pdf_document: 
    latex_engine: xelatex
header-includes:
  - \usepackage{bm}
  - \newcommand{\meps}{\bm{\varepsilon}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



This document summarizes the math behind the model in 
[Meisner et al. (2014)](http://doi.wiley.com/10.1890/13-1933.1).




- $t$ = time
- $T$ = temperature
- $\text{\textbf{X}}(t)$ is a vector giving the number of aphids in each age class on 
  day $t$
- $Y_i(t)$ is the number of parasitoids in age class $i$
- $m_1$ is the number of days parasitoids remain within still-living aphids
- $m$ is the number of days for adult parasitoid emergence
- Aphid survival and reproduction are given in the Leslie matrix $\text{\textbf{L}}(T)$ 
  that depends on temperature $T$ and was parameterized from the individual laboratory
  experiments.
- $z(t)$ is density of unparasitized plus parasitized aphids
- Functions $S(z(t))$ and $S_y(z(t))$ give the survivals of aphids and parasitized aphids

- The parasitoid attack rate depends on temperature $T$, and the proportion of aphids 
  escaping parasitism, $\text{\textbf{A}}(x(t), Y_m(t)|T)$, is assumed to be aggregated
  according to a negative binomial distribution and depends on the density of 
  parasitoid adult females $Y_m(t)$, the total density of aphids $x(t)$... and the 
  stage of the aphid.

- Once parasitized aphids turn into mummies (after $m_1$ days), mummies are assumed to 
  have 100% survival.
- The adult parasitoids have daily survival $s_y$, and adult females appear as mummies 
  emerge at day $m$ with a sex ratio of 1/2.

- Process error (environmental + demographic stochasticity) was included as the 
  random variables $\meps(t)$ and $\meps_y(t)$.


# Overall model

> Note: $\cdot$ <-- means element-wise multiplication


$$
  \text{\textbf{X}}(t+1) = S(z(t)) \cdot \text{\textbf{A}}(x(t), Y_m(t)|T) \cdot
  (\text{\textbf{L}}(T) \text{\textbf{X}}(t)) \cdot e^{\meps(t)}
$$

$$
  Y_1(t+1) = S_y(z(t)) \cdot (1 - \text{\textbf{A}}(x(t), Y_m(t)|T))' 
  \text{\textbf{L}}(T) \text{\textbf{X}}(t)
$$

$$
  Y_i(t+1) = s_i S_y(z(t)) Y_{i-1}(t) e^{\meps(t)}   \text{ for }(i=1, \ldots, m_1)
$$
$$
  Y_i(t+1) = Y_{i-1}(t)   \text{ for }(i=m_1 + 1, \ldots, m - 1)
$$
$$
  Y_m(t+1) = \left( s_y Y_m(t) + \frac{1}{2} Y_{m-1}(t) \right) e^{\meps_y(t)}
$$

# Sub-functions

$$
    \text{\textbf{L}}(T) = 
        \begin{pmatrix}
            0       & f_1   & f_2       & \cdots    & f_{n-1}   \\
            s_1     & 0     & 0         &           & 0         \\
            0       & s_2   & 0         &           & 0         \\
            \vdots  &       &           & \ddots    & \vdots    \\
            0       & 0     & \cdots    & s_{n-1}   & 0    \\
        \end{pmatrix}
$$

where $s_i$ and $f_i$ are age-specific survivorships and fecundities, respectively


$$
  z = \sum_{i=1}^n X_i + \sum_{i=1}^{m_1} Y_i
$$

where $X_i$ is the number of aphids in age group $i$, $Y_i$ is number of parasitoids 
in age group $i$.


$$
  S(z) = \left( 1 + \frac{z}{K} \right)^{-1}
$$

where smaller values of the parameter $K$ correspond to stronger density dependence


Elements of $\text{\textbf{A}}(x,Y_m|T)$ are...

$$
  \left( 1 + \frac{ a \alpha(T) p_i Y_m }{ k(h x + 1) } \right)^{-k}
$$

where...

- $x$ is the total number of aphids (i.e., $x = \sum_{i=1}^n X_i$)
- $a$ is a parameter governing the overall attack rate
- $\alpha(T)$ scales the attack rate according to temperature $T$
- $p_i$ is the relative attack rate on aphids in stage $i$
    - For pi, we used previously reported relative attack rates of 0.12, 0.27, 0.39,
      0.16, and 0.06 for instars I–V, respectively.
- $h$ is the handling time that makes the attack rate depend on aphid density
- $k$ is the aggregation parameter of the negative binomial distribution




$$
  S_y(z) = \left( 1 + \frac{z}{K_y} \right)^{-1}
$$

This has the same form as aphid density-dependent survival, but replaces $K$ with 
$K_y$ so that the strength of density dependence affecting parasitized aphids is
estimated separately from that affecting unparasitized aphids.



$$
  \meps(t) = \meps_d(t) + \meps_e(t)
$$

$\meps(t)$ has normal distribution

$\meps_d(t)$ has a normal distribution with mean zero and variance 
$\min((1 + z(t))^{-1}, 1/2)$ (approximates the variance of a Poisson distribution 
with mean $z$)

$\meps_e(t)$ has a normal distribution with mean zero and variance $\sigma^2_\text{x}$.

correlation $\rho$ between all elements of $\meps_e(t)$ to account for different 
age classes responding in a similar way to environmental fluctuations

Variation in adult female parasitoids was modeled in the same way as that for aphids, 
with a demographic stochasticity term having variance $\min((1 + Y_m(t))^{-1}, 1/2)$ 
and an environmental stochasticity term with variance $\sigma^2_\text{y}$.

the number of aphids and parasitized aphids in a given age class on day $t$ was not 
allowed to exceed the number in the preceding age class on day $t – 1$



## Density dependence

- $K$ strength of density dependence affecting unparasitized aphids
- $K_y$ strength of density dependence affecting parasitized aphids
- $k$ the degree of aggregation in the negative binomial distribution
- $h$ handling time that determined the strength of the type II functional response

parameters $\Delta K$, $\Delta k$, and $\Delta h$ give the difference in values of the parameters between 20ºC and 27ºC

We assumed ... $\Delta K_y / K_y = \Delta K / K$. 

[W]e did not include a parameter $\Delta a$ because the effect of temperature on the 
overall parasitoid attack rate was independently estimated in the short-term 
demographic experiments.

## Variability of system

- $\sigma^2_{\text{x}}$ environmental variability affecting unparasitized and 
  parasitized aphids
- $\rho$ the correlation between instars
- $\sigma^2_{\text{y}}$ the environmental variability affecting adult parasitoids


## Measurement equations

\begin{align}
  x^*(t) &= \left( \sum^n_{i=1} X_i(t) + \sum^{m_l}_{i=1} Y_i(t) \right)
    e^{\gamma_{\text{x}}(t)}\\
  y^*(t) &= \left( \sum^{m-1}_{i=m_l+1} Y_i(t) \right) e^{\gamma_{\text{y}}(t)}
\end{align}


$x^*(t)$ is the observed number of aphids (both unparasitized and parasitized, since 
they cannot be visually distinguished) in a sample

Observations were assumed to be made with measurement error given by the zero-mean normal random variable $\gamma_{\text{x}}(t)$.

We estimated the standard deviation of $\gamma_{\text{x}}(t)$ as 0.2015 by 
performing a repeatability trial on aphid densities between 2 and 440 per plant.


$y^*(t)$, was assumed to be given by a normal random variable $\gamma_{\text{y}}(t)$ 
whose variance $\sigma^2_{\text{m}}$ was estimated during the fit of the time series data.
In addition, we fit the mean value of $\gamma_{\text{y}}(t)$, $M$...

<!---
# Growth rate
# r(T) = exp(r0 + r1 * T(t))

# Parasitoid attack rate:
# a(T) = exp(a0 + a1 * T(t))
-->

